version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'your_database_name'
      MYSQL_USER: 'your_mysql_user'
      MYSQL_PASSWORD: 'your_mysql_password'
      MYSQL_ROOT_PASSWORD: 'your_mysql_root_password'
    ports:
      - "3306:3306"