version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'mydatabaseuser'
      MYSQL_PASSWORD: 'mypassword'
    ports:
      - "3306:3306"